//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class finalTransaction
    {
        public Nullable<long> Id { get; set; }
        public long TransactionId { get; set; }
        public string Name { get; set; }
        public int AccountId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Amount { get; set; }
        public string Purpose { get; set; }
        public string CounterpartyIBAN { get; set; }
        public string yourIBAN { get; set; }
        public bool IsDeleted { get; set; }
    }
}
