//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankAppEntities : DbContext
    {
        public BankAppEntities()
            : base("name=BankAppEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<RoleTBL> RoleTBLs { get; set; }
        public virtual DbSet<TransactionAudit> TransactionAudits { get; set; }
        public virtual DbSet<Transaction> Transactions { get; set; }
        public virtual DbSet<TransactionType> TransactionTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<finalTransaction> finalTransactions { get; set; }
        public virtual DbSet<Transactioncounterpart> Transactioncounterparts { get; set; }
        public virtual DbSet<AccountBalance> AccountBalances { get; set; }
    }
}
