//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionAudit
    {
        public long AuditId { get; set; }
        public Nullable<long> TransactionId { get; set; }
        public Nullable<int> AccountId { get; set; }
        public string Action { get; set; }
        public Nullable<decimal> OldAmount { get; set; }
        public Nullable<decimal> NewAmount { get; set; }
        public Nullable<int> PerformedByUserId { get; set; }
        public System.DateTime PerformedAt { get; set; }
        public string Details { get; set; }
    }
}
