//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transaction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transaction()
        {
            this.Transactioncounterparts = new HashSet<Transactioncounterpart>();
        }
    
        public long TransactionId { get; set; }
        public int AccountId { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public decimal Amount { get; set; }
        public string Purpose { get; set; }
        public int TransactionTypeId { get; set; }
        public Nullable<int> CreatedByUserId { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> DeletedByUserId { get; set; }
        public Nullable<System.DateTime> DeletedAt { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual TransactionType TransactionType { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactioncounterpart> Transactioncounterparts { get; set; }
    }
}
