//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactioncounterpart
    {
        public long TransactionId { get; set; }
        public string CounterpartyIBAN { get; set; }
        public string yourIBAN { get; set; }
        public int TransactionType { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
